### ISSUE TITLE
centos不能成功部署。

### ISSUE THREAD

**Issue by d1107398473** [super-inspire/super-inspire-end#11]
使用python2和python3都一样，执行init.py脚本报键值错误，‘environment’，docker-compose.yaml中并未发现有此键值对。init.sh脚本也不能成功执行。请大佬详细说明部署步。给小白一条活路

**Comment by import-yuefeng** [comment]
问题确认, 在修 > . <

**Comment by import-yuefeng** [comment]
bug已经修复, 测试时为Ubuntu:16.04, 在安装好docker环境下, 使用./init.sh脚本初始化后, 执行docker-compose up即可使用.

关于本次bug修复的代码, 请查阅pr: fix: Fix deploy bug #15
