### ISSUE TITLE
super-inspire显示不出来下相关Linux系统

### ISSUE THREAD

**Issue by onlyDaYue** [super-inspire/super-inspire-end#12]
显示network error

**Comment by import-yuefeng** [comment]
已经确认, 使用的人太多了, 服务临时挂了, 准备在启动新的服务器来平衡负载.> .<

**Comment by import-yuefeng** [comment]
现在可以尝试使用墙外的临时服务器进行体验 http://34.80.61.20:8888
请注意使用代理访问效果较好.

**Comment by onlyDaYue** [comment]
谢谢

**Comment by onlyDaYue** [comment]
现在在线的乌班图命令行不支持netstat命令嘛？

**Comment by import-yuefeng** [comment]
请注意netstat程序并不附加在docker版本的Ubuntu系统中, 如果需要使用请使用ubuntu的包管理工具apt/apt-get来安装
以下是参考指令:
apt-get install net-tools

此外, 为了保护服务器安全, 以及给更多人提供服务, 每一个启动的临时系统暂时只能有一个对外端口可以使用, 想要了解你的端口是什么, 请在打开系统后, 回到创建页, 所指示的外部端口即可, 如何知道IP? 使用curl ip.sb即可获得当前系统所有的公网ip地址

所以你就可以使用临时端口和ip搭配起一个服务, 用于测试.

**Comment by jfliapp** [comment]
墙外的可以了 但是创建失败

**Comment by jfliapp** [comment]
![image](https://user-images.githubusercontent.com/27725921/51725432-1a9d9500-209d-11e9-93b4-4f5d9ff41aab.png)

**Comment by import-yuefeng** [comment]
第一不要在已经关闭的issue里开讨论, 重开一个
第二ubuntu:12.04 没提供, 你可以试试其他的, 最近会支持完整的六个测试系统
