### ISSUE TITLE
为什么会报权限问题?

### ISSUE THREAD

**Issue by seekwe** [super-inspire/super-inspire-end#32]
"/var/build/index.html" is forbidden (13: Permission denied)

**Comment by import-yuefeng** [comment]
感谢使用super-inspire, 这个问题应该是因为文件权限不足, 不过依据当前回报的信息我没办法知道错误原因, 如果可以请提供更多信息方便我进行复现, 感谢

**Comment by seekwe** [comment]
也感谢你开发了如此方便的工具，之前都是用demo的，今天想在自己服务器搭一个，是直接用按说明里下载脚本启动docker-compose，整个下来没有什么操作，真要说可能就是当前用户是root，但是这个抱权限不足是容器内部报，build文件夹直接给777权限也不行

**Comment by wei** [comment]
全新 Ubuntu 无法复现。
试一下 `sudo chown root:root -R /var/build` 再 `docker-compose restart`。

@import-yuefeng p.s. 为啥 clone_html 这步不直接放到 Dockerfile 编译步骤里，这样 `show_distribution`、`detect_pkg_tool` 不用跑了、`wget`、`git` 也不用检查有没有装了，`init.sh` 几乎可以全省略掉 直接装 `docker-compose` 运行就可以了。


-------
```
sudo curl -sSL https://raw.githubusercontent.com/docker/compose/master/script/run/run.sh > /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
```
^推荐直接用 Docker 镜像方式运行的 docker-compose

**Comment by seekwe** [comment]
@wei 忘了补充了,系统是 CentOS 7, 是直接用 Docker 镜像方式运行的 docker-compose 的啊


# git clone https://github.com/super-inspire/super-inspire-end.git
# cd super-inspire-end/
# sudo ./init.sh
# docker-compose up

**Comment by wei** [comment]
全新 CentOS 7 root 全程账户操作无法复现额。运行以下两个试试。看看权限一不一致，不一致的话在母鸡上 `sudo chown root:root -R /var/build` 再试试：

```
[root@demo super-inspire-end]# ls -alt /var/build
total 100
drwxr-xr-x. 20 root root  4096 Feb 19 05:14 ..
drwxr-xr-x.  4 root root  4096 Feb 19 05:14 static
drwxr-xr-x.  3 root root  4096 Feb 19 05:14 .
-rw-r--r--.  1 root root  1041 Feb 19 05:14 service-worker.js
-rw-r--r--.  1 root root   871 Feb 19 05:14 asset-manifest.json
-rw-r--r--.  1 root root 67646 Feb 19 05:14 favicon.ico
-rw-r--r--.  1 root root  2163 Feb 19 05:14 index.html
-rw-r--r--.  1 root root   306 Feb 19 05:14 manifest.json
-rw-r--r--.  1 root root   595 Feb 19 05:14 precache-manifest.3d5a3c00accba2edd3d6c3d9395297ad.js
```
```
[root@demosuper-inspire-end]# docker exec inspire_nginx ls -alt /var/build
total 104
drwxr-xr-x. 1 root root  4096 Feb 19 10:15 ..
drwxr-xr-x. 4 root root  4096 Feb 19 10:14 static
drwxr-xr-x. 3 root root  4096 Feb 19 10:14 .
-rw-r--r--. 1 root root  1041 Feb 19 10:14 service-worker.js
-rw-r--r--. 1 root root   871 Feb 19 10:14 asset-manifest.json
-rw-r--r--. 1 root root 67646 Feb 19 10:14 favicon.ico
-rw-r--r--. 1 root root  2163 Feb 19 10:14 index.html
-rw-r--r--. 1 root root   306 Feb 19 10:14 manifest.json
-rw-r--r--. 1 root root   595 Feb 19 10:14 precache-manifest.3d5a3c00accba2edd3d6c3d9395297ad.js
```

**Comment by import-yuefeng** [comment]
> 全新 Ubuntu 18.04 LTS 无法复现。
> 试一下 `sudo chown root:root -R /var/build` 再 `docker-compose restart`。
> 
> @import-yuefeng p.s. 为啥 clone_html 这步不直接放到 Dockerfile 编译步骤里，这样 `show_distribution`、`detect_pkg_tool` 不用跑了、`wget`、`git` 也不用检查有没有装了，`init.sh` 几乎可以全省略掉 直接装 `docker-compose` 运行就可以了。
> 
> ```
> sudo curl -sSL https://raw.githubusercontent.com/docker/compose/master/script/run/run.sh > /usr/bin/docker-compose
> sudo chmod +x /usr/bin/docker-compose
> ```
> ^推荐直接用 Docker 镜像方式运行的 `docker-compose`

是的, 一开始没考虑到前端的CI, 所以就用了这个很丑陋的办法(为了使得前端代码是最新), 不过写在前端的Dockerfile是最好的选择.

我推荐在前端repo那里加一个travis.yml来实现持续集成, 使得随时都可以得到最新的docker image.
我近来去那边提一个pr来完善这件事情, 使得部署更为简单易行.

**Comment by wei** [comment]
> 我推荐在前端repo那里加一个travis.yml来实现持续集成, 使得随时都可以得到最新的docker image.

赞成，这样更清爽。

**Comment by seekwe** [comment]
@import-yuefeng 唉, 服务器上的权限和你的一样,容器内的文件就报无权限了

**Comment by import-yuefeng** [comment]
> @import-yuefeng 唉, 服务器上的权限和你的一样,容器内的文件就报无权限了,
> 
> 不管用root启动docker-compose还是用root修改权限都不行

抱歉, 基于现在的情况无法定位问题, 如果可以请联系我的telegram: 12344211546, 可以在线联调一下, 查看具体的问题.

**Comment by seekwe** [comment]
@import-yuefeng 你的telegram设置了好像只能好友发送,你试试加我 seekwe

**Comment by import-yuefeng** [comment]
之前已添加 :)
